[versions]
#noinspection GradleDependency
accompanist = "0.36.0"
#noinspection GradleDependency
activityCompose = "1.9.3"
#noinspection AndroidGradlePluginVersion
agp = "8.7.2"
appcompat = "1.7.0"
#noinspection GradleDependency
axConstraintLayout = "1.1.0-alpha13"
#noinspection GradleDependency
axDataStore = "1.1.2"
axHilt = "1.2.0"
axLifecycle = "2.8.7"
#noinspection GradleDependency
axNavigation = "2.8.3"
axPalette = "1.0.0"
axTest = "1.6.1"
axTestExtJunit = "1.2.1"
axTestExtTruth = "1.6.0"
axTestRunner = "1.6.2"
axTestUIAutomator = "2.3.0"
axWindow = "1.3.0"
#noinspection GradleDependency
coil = "2.6.0"
coil3 = "3.0.1"
#noinspection GradleDependency
composeBom = "2024.12.01"
#noinspection GradleDependency
coreKtx = "1.13.1"
coroutines = "1.9.0"
espressoCore = "3.6.1"
glance = "1.1.1"
hilt = "2.53.1"
#hilt248 = "2.48.1"
#hilt249 = "2.49"
#hilt251 = "2.51.1"
#hilt253 = "2.53" #supposed fix for kotlin unsupported metadata version
#hilt253 = "2.53.1" #supposed fix for no dependencies reported for generated source
#horologist = "0.6.19"
#noinspection GradleDependency
kotlin = "2.1.0"
#kotlin200 = "2.0.0"
#kotlin210 = "2.1.0"
kotlin_logging = "7.0.3"
slf4j = "2.0.16"
kotlinx_immutable = "0.3.8"
kotlinx-serialization-json = "1.7.3"
#noinspection GradleDependency
ksp = "2.1.0-1.0.29"
#ksp200 = "2.0.0-1.0.24"
#ksp210 = "2.1.0-1.0.29"
#noinspection GradleDependency
jdkDesugar = "1.2.2"
junit = "4.13.2"
#noinspection GradleDependency
material = "1.7.6"
#noinspection GradleDependency
media3 = "1.4.1"
#noinspection GradleDependency
okhttp = "4.11.0"
robolectric = "4.13"
#noinspection GradleDependency
roborazzi = "1.12.0"
rome = "1.18.0"
#noinspection GradleDependency
room = "2.6.1"
secrets = "2.0.1"
#noinspection GradleDependency
transportApi = "3.0.0"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }

androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }

androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
androidx-compose-material3-adaptive-navigationSuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
androidx-compose-material3Window = { module = "androidx.compose.material3:material3-window-size-class" }

androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

#androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
#androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
#what do these provide?

androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-googlefonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test = { module = "androidx.compose.ui:ui-test" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "axConstraintLayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "axDataStore" }

androidx-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-appwidget-testing = { module = "androidx.glance:glance-appwidget-testing", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-glance-testing = { module = "androidx.glance:glance-testing", version.ref = "glance" }

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "axLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "axLifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "axLifecycle" }
androidx-lifecycle-runtime-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "axLifecycle"}
androidx-lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "axLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "axLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "axLifecycle" }

androidx-media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-midi = { module = "androidx.media3:media3-exoplayer-midi", version.ref = "media3" }
androidx-media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-test-utils = { module = "androidx.media3:media3-test-utils", version.ref = "media3" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

#mp3agic = { module = "com.mpatric:mp3agic", version = "0.9.1" }
nextlib = { module = "com.github.anilbeesetti.nextlib:nextlib-media3ext", version = "0.8.1" }
#lottie-compose = { module = "com.airbnb.android:lottie-compose", version = "6.6.2" } #airbnb???

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "axNavigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "axNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "axNavigation" }

androidx-palette = { module = "androidx.palette:palette", version.ref = "axPalette" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

androidx-test-core = { module = "androidx.test:core", version.ref = "axTest" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "axTestExtJunit" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "axTestExtTruth" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "axTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "axTestRunner" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "axTestUIAutomator" }

androidx-window = { module = "androidx.window:window", version.ref = "axWindow" }
androidx-window-core = { module = "androidx.window:window-core", version.ref = "axWindow" }

coil-kt-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil3-kt-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
core-jdk-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "jdkDesugar" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "axHilt" }
androidx-hilt-ext-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "axHilt" }
dagger-hiltandroidplugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

#horologist-audio-ui = { module = "com.google.android.horologist:horologist-audio-ui", version.ref = "horologist" }
#horologist-composables = { module = "com.google.android.horologist:horologist-composables", version.ref = "horologist" }
#horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
#horologist-compose-material = { module = "com.google.android.horologist:horologist-compose-material", version.ref = "horologist" }
#horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
#horologist-images-coil = { module = "com.google.android.horologist:horologist-images-coil", version.ref = "horologist" }
#horologist-media-data = { module = "com.google.android.horologist:horologist-media-data", version.ref = "horologist" }
#horologist-media-ui = { module = "com.google.android.horologist:horologist-media-ui", version.ref = "horologist" }
#horologist-roboscreenshots = { module = "com.google.android.horologist:horologist-roboscreenshots", version.ref = "horologist" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin_logging"}
slf4j-log = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx_immutable" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
roborazzi-rule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
#rometools-modules = { module = "com.rometools:rome-modules", version.ref = "rome" }
rometools-rome = { module = "com.rometools:rome", version.ref = "rome" }
transport-api = { group = "com.google.android.datatransport", name = "transport-api", version.ref = "transportApi" }

wavy-slider = { module = "ir.mahozad.multiplatform:wavy-slider", version = "1.3.0" }
#play-services-cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "playServicesCastFramework" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
#android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
#kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
